[package]
name = "progetto_g32"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scrap = "0.5"
rdev = "0.4"
lazy_static = "1.5.0"
rodio = "0.14.0"
sysinfo = "0.25.0"
chrono = "0.4.38"


