[package]
name = "progetto_g32"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.26"
rdev = "0.4"
lazy_static = "1.5.0"
scrap = "0.5.0"  # o la versione più recente disponibile
